In [1]:
import pandas as pd

In [3]:
df = pd.read_json(r"C:\Users\joaoe.DESKTOP-53TM428\OneDrive\Documents\Pandas\Estudos\receitas.json",encoding="utf-8")
df

                                            receitas
0  {'titulo': 'Bolo de Chocolate', 'tempo_preparo...
1  {'titulo': 'Salada Caesar', 'tempo_preparo': '...
2  {'titulo': 'Pasta ao Pesto', 'tempo_preparo': ...

In [8]:
#Analise Total de Ingredientes por Receitas
receitas_expandidas = []
for receita in df['receitas']:
   total_ingredientes = len(receita['ingredientes'])
   receita_info = {
      'titulo': receita['titulo'],
      'tempo_preparo' : receita['tempo_preparo'],
      'porcoes' : receita['porcoes'],
      'total_ingredientes' : total_ingredientes
   }
   receitas_expandidas.append(receita_info)

In [9]:
print(receitas_expandidas)

[{'titulo': 'Bolo de Chocolate', 'tempo_preparo': '45 minutos', 'porcoes': 8, 'total_ingredientes': 5}, {'titulo': 'Salada Caesar', 'tempo_preparo': '20 minutos', 'porcoes': 4, 'total_ingredientes': 4}, {'titulo': 'Pasta ao Pesto', 'tempo_preparo': '30 minutos', 'porcoes': 2, 'total_ingredientes': 5}]

In [10]:
df_expandido = pd.DataFrame(receitas_expandidas)
df_expandido

              titulo tempo_preparo  porcoes  total_ingredientes
0  Bolo de Chocolate    45 minutos        8                   5
1      Salada Caesar    20 minutos        4                   4
2     Pasta ao Pesto    30 minutos        2                   5