In [1]:
import pandas as pd

In [2]:
dados = {
    'Nome' : ['Alice','Bob','Charlie'],
    'Idade' : [24,30,22],
    'Cidade' : ['São Paulo','Rio de Janeiro','Belo Horizonte']
}

In [4]:
df = pd.DataFrame(dados)

In [5]:
df

      Nome  Idade          Cidade
0    Alice     24       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     22  Belo Horizonte

In [9]:
df.head(1)

    Nome  Idade     Cidade
0  Alice     24  São Paulo

In [11]:
df.tail(1)

      Nome  Idade          Cidade
2  Charlie     22  Belo Horizonte

In [21]:
dados_notas = {
    'Nome' : ['Alice','Bob','David','Eva','Charlie'],
    'Matematica' : [85,90,78,88,92],
    'Fisica' : [80,75,88,85,95],
    'Quimica' : [78,82,85,80,88]
}

In [22]:
df_notas = pd.DataFrame(dados_notas)

In [23]:
df_notas

      Nome  Matematica  Fisica  Quimica
0    Alice          85      80       78
1      Bob          90      75       82
2    David          78      88       85
3      Eva          88      85       80
4  Charlie          92      95       88

In [24]:
# Calcular a media de notas
df_notas['Média'] = df_notas[['Matematica','Fisica','Quimica']].mean(axis=1)
df_notas

      Nome  Matematica  Fisica  Quimica      Média
0    Alice          85      80       78  81.000000
1      Bob          90      75       82  82.333333
2    David          78      88       85  83.666667
3      Eva          88      85       80  84.333333
4  Charlie          92      95       88  91.666667

In [28]:
#Indentificar Alunos Aprovados com nota boa(media >= 82.5)
alunos_aprovados = df_notas[df_notas['Média'] >= 82.5]
alunos_aprovados

      Nome  Matematica  Fisica  Quimica      Média
2    David          78      88       85  83.666667
3      Eva          88      85       80  84.333333
4  Charlie          92      95       88  91.666667

In [29]:
#Exibir a média e os alunos aprovados
df_notas[['Nome','Média']]

      Nome      Média
0    Alice  81.000000
1      Bob  82.333333
2    David  83.666667
3      Eva  84.333333
4  Charlie  91.666667

In [30]:
alunos_aprovados[['Nome','Média']]

      Nome      Média
2    David  83.666667
3      Eva  84.333333
4  Charlie  91.666667