In [1]:
import pandas as pd

In [2]:
df_produtos = pd.read_csv("dados/ecommerce_user_behavior_8000.csv")
df_produtos

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [3]:
df_produtos.head(8)

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
5,6.0,56.0,Female,Desktop,26.60,1.0,12.0,7.0,1.0,1.0,0.0,28.40,13.90,1.0
6,7.0,36.0,Male,Mobile,7.60,11.0,11.0,6.0,1.0,1.0,1.0,4.51,13.12,1.0
7,8.0,40.0,Female,Mobile,26.98,7.0,5.0,2.0,1.0,0.0,0.0,33.34,12.61,1.0

In [5]:
df_produtos.tail(8)

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
7992,7993.0,36.0,Female,Mobile,5.90,5.0,7.0,0.0,1.0,1.0,1.0,4.69,99.40,1.0
7993,7994.0,29.0,Male,Mobile,3.15,18.0,3.0,9.0,1.0,0.0,1.0,2.59,11.49,1.0
7994,7995.0,32.0,Female,Desktop,7.85,1.0,6.0,5.0,1.0,1.0,0.0,10.80,18.08,1.0
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [6]:
df_produtos.shape

(8000, 14)

In [7]:
df_produtos.dtypes

user_id               float64
age                   float64
gender                    str
device_type               str
time_on_site          float64
pages_viewed          float64
previous_purchases    float64
cart_items            float64
discount_seen         float64
ad_clicked            float64
returning_user        float64
avg_session_time      float64
bounce_rate           float64
purchase              float64
dtype: object

In [8]:
df_produtos.sort_values(by='cart_items',ascending=False)

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
7978,7979.0,25.0,Male,Mobile,24.97,2.0,5.0,9.0,1.0,1.0,0.0,21.93,73.68,1.0
8,9.0,28.0,Female,Mobile,10.90,14.0,7.0,9.0,0.0,0.0,1.0,13.80,85.46,1.0
7970,7971.0,42.0,Female,Mobile,15.44,3.0,14.0,9.0,0.0,1.0,0.0,9.57,37.29,1.0
1649,1650.0,25.0,Male,Mobile,19.01,10.0,10.0,9.0,0.0,1.0,0.0,9.69,18.68,NaN
6374,6375.0,NaN,Male,Mobile,3.80,10.0,5.0,9.0,0.0,1.0,1.0,4.58,64.37,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7737,7738.0,52.0,Female,Mobile,28.73,10.0,13.0,NaN,0.0,1.0,1.0,16.84,98.35,1.0
7763,7764.0,40.0,Female,Desktop,27.11,4.0,13.0,NaN,1.0,0.0,1.0,22.63,80.84,1.0
7868,7869.0,35.0,Female,Desktop,2.76,2.0,5.0,NaN,1.0,0.0,1.0,1.50,60.10,1.0
7949,7950.0,50.0,NaN,Mobile,1.62,9.0,13.0,NaN,1.0,0.0,1.0,1.96,82.07,1.0
7976,7977.0,26.0,Male,Mobile,18.55,12.0,12.0,NaN,0.0,1.0,1.0,27.73,23.00,1.0

In [9]:
df_produtos['device_type'].value_counts()

device_type
Mobile     4685
Desktop    2365
Tablet      790
Name: count, dtype: int64